### ISSUE TITLE
3. Excluir

### ISSUE THREAD

**Issue by Anajuliamantovani** [Anajuliamantovani/Projeto-arvores-Binarias#3]
When the user select Excluir option, ask for the CPF, search in the binary tree. If not exist, will appear a message "CPF não cadastrado".
If not, delete from the binary tree and from the linked list. It's not necessary delete from the dynamic list because the data will be inaccessible.

Quando for selecionada a opção Excluir, pedir o CPF, buscar na Árvore Binária. Se não existir, emitir a
mensagem CPF não cadastrado.
Senão, excluir da Árvore Binária e da Lista Ligada. Não é necessário excluir da Lista Dinâmica pois os dados
estarão inacessíveis.

**Comment by Joao-victor-da-silva** [comment]
### Explicando

Eu peguei as funções Excluir da lista ligada e da arvore binarias do projeto do professor, as renomeei e troquei e substitui as variáveis, depois eu simplesmente chamei elas para função excluir com o parâmetro tempCpf e tempNRegisstro que conseguir na função procurar cpf.

```c
void Excluir()
{
    if(procurarCpf(-1) == 0)
    {
        return;
    }
    ABexcluir(tempCPF);
    LLexcluir(tempNRegistro);
}
```

### Resultado antes de Excluir 

![Image](https://github.com/user-attachments/assets/68663a7e-f27c-4c9a-8038-88705e9aabb0)

### Depois de expluir 

![Image](https://github.com/user-attachments/assets/b6d8298f-ce15-4665-adeb-00293fa30513)
