### ISSUE TITLE
1. Adicionar

### ISSUE THREAD

**Issue by Anajuliamantovani** [Anajuliamantovani/Projeto-arvores-Binarias#5]
When you select the option Adicionar, the program will ask for the CPF;
The system will search if the CPF already exists on the binary tree, if exist will appear a message saying that the CPF it's registered, if not ask for the other data, add on dynamic list, getting the register number, add on the binary tree and linked list.

Quando for selecionada a opção Adicionar, o programa deve pedir pelo CPF.
Depois pesquisar se o CPF já está na árvore binária, se estiver dizer que o CPF já está cadastrado.
Senão, pedir os outros dados, adicionar na Lista Dinâmica, pegando o número do registro, adicionar na Árvore Binária e na Lista Ligada.

**Comment by Anajuliamantovani** [comment]
![Image](https://github.com/user-attachments/assets/bd0a33c7-bb65-4f50-807d-0884378f4657)

**Comment by Joao-victor-da-silva** [comment]
Adicionar essa condição 
```c
if(idade > 18)
{
Printf("Maior de idade");
}
```
