### ISSUE TITLE
5. Relatório

### ISSUE THREAD

**Issue by Anajuliamantovani** [Anajuliamantovani/Projeto-arvores-Binarias#7]
When the user select Relatorio option, use linked list to print all records sorted by name.

Quando for selecionada a opção Relatório, usar a Lista Ligada para imprimir todos os registro ordenados por nome.

**Comment by Joao-victor-da-silva** [comment]
### Explicação 

Para fazer o relatório funcionar, bastou copiar as funções do professor  da lista ligada, referente a imprimir e depois substituir pelas nossas variáveis, logo depois  colocar a função printarEscolha() com o parâmetro do numero de registro pegado da lista ligada 

```c
void imprimir() {
    int valor = 0;
    if(LLinicio != NULL) {
        paraInicio();
        while(corrente(&valor)) {
            printarEscolha(valor);
            paraProximo();
        }
        printf("\n");
    }
}

```

### Resultado 

![Image](https://github.com/user-attachments/assets/3b2b9003-6bed-40e7-b666-ef1c56728fe9)
